### ISSUE TITLE
runValidatorAsDeamon.bat bei Leerzeichen in den Pfaden

### ISSUE THREAD

**Issue by dsshad** [LandrixSoftware/XRechnung-for-Delphi#29]
Ich wollte jetzt mal die runValidatorAsDeamon.bat ausprobieren. Dabei scheinen die Leerzeichen in den Pfaden Probleme zu machen. Hier die Ausgabe:

> C:\SVN\APP_1\trunk\00 aaa\02 bbb\XInvoice\Distribution>.\java\bin\java.exe -jar .\validator\validationtool-1.5.0-standalone.jar -s C:\SVN\APP_1\trunk\00 aaa\02 bbb\XInvoice\Distribution\validator-configuration30x\scenarios.xml -r C:\SVN\APP_1\trunk\00 aaa\02 bbb\XInvoice\Distribution\validator-configuration30x -D -X
KoSIT Validator version 1.5.0
Mixed mode configuration detected. Use either daemon mode or cli mode commandline options. They are mutual exclusive. Will ignore cli mode options
java.lang.IllegalArgumentException: Not a valid path for scenario definition specified: '**C:\SVN\APP_1\trunk\00**'
        at de.kosit.validationtool.cmd.Validator.assertFileExistance(Validator.java:330)
        at de.kosit.validationtool.cmd.Validator.lambda$getConfiguration$0(Validator.java:191)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at de.kosit.validationtool.cmd.Validator.getConfiguration(Validator.java:200)
        at de.kosit.validationtool.cmd.Validator.startDaemonMode(Validator.java:122)
        at de.kosit.validationtool.cmd.Validator.mainProgram(Validator.java:84)
        at de.kosit.validationtool.cmd.CommandLineOptions.call(CommandLineOptions.java:173)
        at de.kosit.validationtool.cmd.CommandLineOptions.call(CommandLineOptions.java:40)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at de.kosit.validationtool.cmd.CommandLineApplication.mainProgram(CommandLineApplication.java:82)
        at de.kosit.validationtool.cmd.CommandLineApplication.main(CommandLineApplication.java:54)
Not a valid path for scenario definition specified: **C:\SVN\APP_1\trunk\00**
2024-10-31 11:14:52 [ERROR] Not a valid path for scenario definition specified: '**C:\SVN\APP_1\trunk\00**'

Beim ersten Leerzeichen geht es nicht weiter, wenn ich es richtig sehe.

Dürfen in den Pfaden keine Leerzeichen vorkommen?

**Comment by landrix** [comment]
Hab die .bat mal angepasst, hilft das?

**Comment by dsshad** [comment]
Ja, jetzt konnte ich die Datei ausführen und den Daemon-Mode starten.
Weiß zwar gerade nicht, was ich damit anstellen soll, aber das Problem mit den Leerzeichen im Pfad ist auf jeden Fall erledigt, danke.

**Comment by landrix** [comment]
wenn jemand die REST-API schreibt, kann er XRechnungen gegen den Daemon validieren, was wohl etwas schneller geht, als per Kommandozeile
